# Generated by Django 5.0.6 on 2024-07-04 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='ventas',
            field=models.IntegerField(default=0),
        ),
    ]
