# Generated by Django 5.0.6 on 2024-07-04 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inventario', '0002_articulo_ventas'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='entradas',
            field=models.IntegerField(default=0),
        ),
    ]
