# Generated by Django 5.0.6 on 2024-07-07 14:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inventario', '0003_articulo_entradas'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='fecha_registro',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
